version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '3000:5002'
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    # command: npx prisma migrate deploy && npm run start:prod
    volumes:
      - ./:/app/
